Repository jwstegemann/fritz2-kitchensink, pull requests merged in 2021-06, with the labels that each got.

#56 Adapt changes of alert API
  build.gradle.kts
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/formControlDemo.kt
Labels: bug

#55 Add slider demo
  src/jsMain/kotlin/dev.fritz2.kitchensink/app.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/formControlDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/sliderDemo.kt
Labels: enhancement

#54 Polish and Extend DataTable demo
  build.gradle.kts
  src/commonMain/kotlin/dev/fritz2/kitchensink/datatable/dataTableModel.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/dataTableDemo.kt
Labels: documentation

#53 Added new `linkButton` to component demo
  src/jsMain/kotlin/dev.fritz2.kitchensink/app.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/base/base.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/buttonDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/iconsDemo.kt
Labels: documentation, enhancement

#65 Fix wrong import errros
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/dataTableDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/formControlDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/selectDemo.kt
Labels: bug

#66 Repair validation
  src/commonMain/kotlin/dev/fritz2/kitchensink/formControl/formControlModel.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/formControlDemo.kt
Labels: bug
