Repository jwstegemann/fritz2-kitchensink, pull requests merged in 2021-04, with the labels that each got.

#35 Fixed a button in ToastDemo
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/toastDemo.kt
Labels: bug

#37 Extend doc of Stack Component
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/stackDemo.kt
Labels: documentation

#38 Fix Version of Kitchensink project
  build.gradle.kts
Labels: bug

#42 Extends of ColorScheme approach
  src/jsMain/kotlin/dev.fritz2.kitchensink/app.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/base/base.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/base/themes.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/alertDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/buttonDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/checkboxesDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/colorDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/fileDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/flexBoxDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/formControlDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/gridBoxDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/iconsDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/modalDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/popoverDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/radioDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/responsiveDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/spinnerDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/stackDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/stylingDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/switchDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/toastDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/welcome.kt
Labels: documentation, enhancement

#44 Adjust kitchensink for Alert-API changes
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/alertDemo.kt
Labels: documentation

#45 Adjust path to background & font color
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/colorDemo.kt
Labels: enhancement

#39 Show underlying version of fritz2 in kitchensink-demo
  build.gradle.kts
  src/jsMain/kotlin/dev.fritz2.kitchensink/app.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/base/base.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/base/properties.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/gettingStarted.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/iconsDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/welcome.kt
  src/jsMain/resources/index.html
Labels: enhancement

#47 Small refactorings
  src/jsMain/kotlin/dev.fritz2.kitchensink/app.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/base/base.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/alertDemo.kt
Labels: enhancement

#50 removed duplicate variants section in `buttonDemo`
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/buttonDemo.kt
Labels: bug

#49 Add DataTable demo site
  build.gradle.kts
  src/commonMain/kotlin/dev/fritz2/kitchensink/datatable/dataTableModel.kt
  src/commonMain/kotlin/dev/fritz2/kitchensink/formControl/formControlModel.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/app.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/checkboxesDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/dataTableDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/formControlDemo.kt
  src/jsMain/kotlin/dev.fritz2.kitchensink/demos/selectDemo.kt
Labels: documentation
